### ISSUE TITLE
Workflow status method

### ISSUE THREAD

**Issue by tonyc** [curationexperts/mira#396]
Write a method that returns a symbol based on the current workflow status of an object.

**Comment by tonyc** [comment]
Blocks #335, #336

**Comment by mark-dce** [comment]
Possible state list
* NEW - draft copy created, never published - note that there's no way (and no need) to tell if a draft copy is edited prior to publication
* PUBLISHED - draft has been copied to production; production copy matches draft copy (i.e. no further edits)
* EDITED - published copy has been created; draft has been uptaded since publication (updates may occur manually in the edit form  or via template or XML import)

Transitions between the above states should be tracked either on the object or in a log file - see #354

The following state transitions need to be tracked somehow:
* REVERTED - pending changes to draft overwritten by production copy
* PURGED - draft and published copies deleted

**Comment by tonyc** [comment]
Closed via https://github.com/curationexperts/tufts_models/pull/31
