### ISSUE TITLE
Transient build error

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#590]
Commit: 0f0b166
Seed: 58538

I think these were the same as

commit: 33dcbac
seed: 51708

Failures:
  1) Batch::XmlImportsController an admin GET 'show' happy path returns http success
     Failure/Error: let(:batch_xml_import) { FactoryGirl.create(:batch_xml_import, uploaded_files: uploaded_files) }
       <ActiveFedora::Base (class)> received :find with unexpected arguments
         expected: ("tufts:my-pid", {:cast=>true})
              got: ("draft:3")
       Diff:
        
       @@ -1,2 +1,2 @@
       -["tufts:my-pid", {:cast=>true}]
       +["draft:3"]
       
        Please stub a default value first if message might be received with other args as well. 
     # ./app/services/build_record_service.rb:31:in `run'
     # ./app/parsers/metadata_xml_parser.rb:88:in `block in validate_generated_records'
     # ./app/parsers/metadata_xml_parser.rb:120:in `each_digital_object'
     # ./app/parsers/metadata_xml_parser.rb:83:in `validate_generated_records'
     # ./app/parsers/metadata_xml_parser.rb:20:in `validate'
     # ./spec/controllers/batch/xml_imports_controller_spec.rb:203:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/batch/xml_imports_controller_spec.rb:213:in `block (5 levels) in <top (required)>'
  2) Batch::XmlImportsController an admin GET 'edit' assigns @pids_that_already_exist
     Failure/Error: expect(assigns[:pids_that_already_exist]).to eq ['tufts:1']
       
       expected: ["tufts:1"]
            got: ["tufts:1", "tufts:3"]
       
       (compared using ==)
     # ./spec/controllers/batch/xml_imports_controller_spec.rb:68:in `block (4 levels) in <top (required)>'

**Comment by val99erie** [comment]
I'm unable to reproduce these errors.  I examined the tests, and I don't see anything obvious that could be wrong.

I could add a default stub ahead of the test stub, as the first error message suggests, but that might end up masking a problem.  Since the test stub is written as "allow" instead of "expect", it probably doesn't matter if the "find" method is being called with other arguments, but then I would expect the test to fail consistently, which isn't the case.

Until we understand why this error occurs, I'd recommend we do nothing to try to fix it.

**Comment by mark-dce** [comment]
Unable to reproduce this issue.
