### ISSUE TITLE
Intermittent build eror

### ISSUE THREAD

**Issue by tonyc** [curationexperts/mira#611]
--seed 58151

  1) PublishService#run when a published version does not exist results in a published copy of the draft
     Failure/Error: expect { subject.run }.to change { TuftsImage.exists?(published_pid) }.
       expected result to have initially been false, but was true
     # ./spec/services/publish_service_spec.rb:73:in `block (4 levels) in <top (required)>'

**Comment by mark-dce** [comment]
same issue on commit x with seed 55542

**Comment by jcoyne** [comment]
But I can't reproduce that error locally. Even when specifiying the seed.

**Comment by mark-dce** [comment]
Hmm - I still have a build hanging around on Travis showing it: https://travis-ci.org/curationexperts/mira/builds/66237849

**Comment by tonyc** [comment]
Yeah, I can't seem to be able to reproduce this anymore, along with mark's SHA and seed.

**Comment by mark-dce** [comment]
This just happened again with commit eb722c4 and seed 56823 for Justin's most recent PR.   I'm re-running travis so I can get a green before merge, but it's definitely there...

Maybe you need a truly empty jetty for this to show up???  Maybe try `rake jetty:clean` before trying to reproduce locally?

**Comment by jcoyne** [comment]
@mark-dce we are starting with a clean jetty, see https://github.com/curationexperts/mira/blob/master/spec/spec_helper.rb#L43

**Comment by val99erie** [comment]
This error is caused by the fact that an object with the published PID exists at the beginning of the test.  The test assumes that the object doesn't exist, but there is nothing in the test setup that guarantees that object doesn't exist.

In production, we shouldn't ever have a problem with published PIDs being taken out of turn (even though we have no logic in place to reserve the published PID) because we always create draft objects first and then publish them.

However, in the test environment, we sometimes manually create draft or published objects, without using that production workflow.  I'm guessing that occasionally the sequencer for the published namespace gets ahead of the draft namespace, so there is a clash, and a published object exists when we didn't expect it to.

Since the test explicitly assumes that this object doesn't exist, I'll add a check in the test setup to make sure that condition is correct.
