### ISSUE TITLE
Export batch keeps adding lines

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/mira#614]
1) Search for records
2) select 2 of them
3) Click "Export" and "Continue"
4) You'll see 2 items in the batch.
5) Click the back button in the browser. The two items should still be checked.
6) Click "Export" and "Continue"
7) Now there is a new batch, but it has 4 items on it (2 are repeated). I'd expect only 2 items.

**Comment by val99erie** [comment]
Here's another test case of the same problem:

Follow steps 1 thru 5, as Justin describes above.  Then:
6. Uncheck one of the 2 records, so now there is only one record checked
7. Click 'Export' and 'Continue'
8. Now the new batch has 3 entries (1 entry is repeated)

This tells me that we can't just do a pids.uniq in the controller, because the PID that you unchecked will still appear in the batch, even though it shouldn't be there.

**Comment by tonyc** [comment]
Adding to this, it seems that <input> elements are only ever being added to the form, not removed.  

See the "serialzeCheckboxes" JS function in batch_select_all.js.

You could probably fix it by removing all of the hidden fields in the form before serializing it.

**Comment by val99erie** [comment]
Yeah, I was thinking that, but I can't blindly remove all hidden fields because I would lose important things like Rails' authenticity_token.  So, I have to search for certain hidden fields to remove.

**Comment by val99erie** [comment]
@jcoyne Were you using Firefox when you saw this problem?

**Comment by jcoyne** [comment]
@val99erie yes

**Comment by val99erie** [comment]
Tony and I couldn't get this problem to show up consistently.  It shows up inconsistently in Firefox, but we could never get it to show up in Chrome.  We think this is a browser cacheing problem.  Tony committed a fix that should take care of the problem
