### ISSUE TITLE
Batch ingest of .tif gets Internal Server Error on initial ingest, able to ingest at batch summary for some, not all images

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/mira#635]
I just batched ingested a set of images (See batch id 137).  The initial batch gets an "Internal Server Error" message on some of the images, but not all.  When I review the batch, I get the expected warning:

Warning: Metadata exists for the following files that have not been updated:
14.8502-23AM.2.tif
14.8502-30AM.40.tif
14.8502-30AM.47.tif
14.8502-30AM.50.tif
14.8502-30AM.52.tif
14.8502-30AM.57.tif
14.8502-30AM.63.tif
14.8502-30AM.64.tif
14.8502-30AM.65.tif

add additional files to this batch

If I add a single additional file from this list, I am able to ingest that image.  If I do a batch, some will ingest and some will get the "internal server error" warning.  

I was able to reduplicate this.  See batch 138.

**Comment by mark-dce** [comment]
@Alexandermay - we were trying to fix another error with image creation and had the derivative generator in a bad state.  @acozine and I were able to correct the issue with image derivatives late this afternoon.  All of the images in your batches have now been processed, with one exception - draft:737 - "National Gallery, London." (also draft:766)

For whatever reason, that image raises errors when ImageMagick tries to read and transform it.  Since this is an issue with the underlying tool, we may not be able to resolve the issue for this specific TIFF.  I have, however, opened a separate ticket for it as #637.

You can view the rest of the images using:  
Batch 137: http://mira.curationexperts.com/catalog?utf8=%E2%9C%93&per_page=50&search_field=batch&q=137  
Batch 138: http://mira.curationexperts.com/catalog?utf8=%E2%9C%93&per_page=50&search_field=batch&q=138
