### ISSUE TITLE
Revert after only updating a binary datastream results in "something went wrong" error

### ISSUE THREAD

**Issue by e2d2** [curationexperts/mira#644]
For object draft:MS210.004.001.00001.00006 
First I published the object.
Then I swapped out the binary file for something else. This resulted in the object being marked as "edited". I then clicked "revert" and it gave me the error message.

Obviously since binary datastreams are not versioned, there is no way to "revert" once the datastream has been replaced. However, revert capability in this instance is confusing.

**Comment by mark-dce** [comment]
This is an edge case of the datastream checksumming issue.  The published version is not getting it's checksum updated when we attach a new file to the object.

**EXAMPLE** (see the MD5 Digests)
*New Unpublished Object - draft:968*
```xml
<foxml:datastream ID="Archival.pdf" STATE="A" CONTROL_GROUP="E" VERSIONABLE="false">
    <foxml:datastreamVersion ID="Archival.pdf.0" LABEL="3_1_Manual_BC906_USA.pdf" CREATED="2015-06-26T23:14:45.342Z" MIMETYPE="application/pdf">
      <foxml:contentDigest TYPE="MD5" DIGEST="3b61be0b52bd6ac310bb53f52b1062f7"/>
      <foxml:contentLocation TYPE="URL" REF="file:///demo/bucket/data01/tufts/sas/archival_pdf/968.archival.pdf"/>
  </foxml:datastreamVersion>
</foxml:datastream>
```

*Published Object - tufts:968*
```xml
<foxml:datastream ID="Archival.pdf" STATE="A" CONTROL_GROUP="E" VERSIONABLE="false">
    <foxml:datastreamVersion ID="Archival.pdf.0" LABEL="3_1_Manual_BC906_USA.pdf" CREATED="2015-06-26T23:14:45.342Z" MIMETYPE="application/pdf">
      <foxml:contentDigest TYPE="MD5" DIGEST="3b61be0b52bd6ac310bb53f52b1062f7"/>
      <foxml:contentLocation TYPE="URL" REF="file:///demo/bucket/data01/tufts/sas/archival_pdf/968.archival.pdf"/>
  </foxml:datastreamVersion>
</foxml:datastream>
```

**Draft object datastream updated - draft:968**
```xml
<foxml:datastream ID="Archival.pdf" STATE="A" CONTROL_GROUP="E" VERSIONABLE="false">
  <foxml:datastreamVersion ID="Archival.pdf.2" LABEL="AK Page 4.pdf" CREATED="2015-06-26T23:22:56.253Z" MIMETYPE="application/pdf">
    <foxml:contentDigest TYPE="MD5" DIGEST="6244c50d48c558344cd85b882440a719"/>
    <foxml:contentLocation TYPE="URL" REF="file:///demo/bucket/data01/tufts/sas/archival_pdf/968.archival.pdf"/>
  </foxml:datastreamVersion>
</foxml:datastream>
```

At this point, the published version of the datastream has not been modified and still has the old checksum.  When you delete the draft and try to copy the export of the production foxml, you get a fedora error because the checksum no longer matches the file save on disk.

Here's an excerpt from the production.log after the revert operation:

```text
I, [2015-06-26T23:12:09.750746 #26051]  INFO -- : Started POST "/records/draft:967/revert" for 75.149.149.10 at 2015-06-26 23:12:09 +0000
I, [2015-06-26T23:12:09.752089 #26051]  INFO -- : Processing by RecordsController#revert as HTML

. . . 

I, [2015-06-26T23:12:09.955931 #26051]  INFO -- : Completed 500 Internal Server Error in 204ms
F, [2015-06-26T23:12:09.957263 #26051] FATAL -- : 
Rubydora::FedoraInvalidRequest (See logger for details):
  app/services/fedora_object_copy_service.rb:14:in `run'
  app/services/revert_service.rb:11:in `run'
  app/controllers/records_controller.rb:77:in `revert'
```

**Comment by mark-dce** [comment]
The possible options I can see would be:

1. re-publish the object immediately upon managing data steams - this won't work because there may also be pending metadata edits that should not be published
1. purge the checksums in the FedoraObjectCopyService and force Fedora to recalculate checksums - this breaks the chain of authenticity in that something could potentially happen between the file attachment being uploaded and the object being reverted that would corrupt the file - a newly calculated checksum wouldn't identify that issue.
1. suppress the edited flag and revert option - this probably can't work because someone might have changed metadata at the same time (the workflow takes you to the edit metadata page every time you update data streams)
1. if there's a published version, update the archival content datastream(s) on the published version at the same time we update it on the draft - we'd have to be careful about managing the published_at and edited_at timestamps so they reflect publish and revert correctly

**Comment by e2d2** [comment]
Mark,
I think my preference would be for option 4. Although I’m curious what you could imagine happening in scenario 2 that would corrupt the file.
Erin

**Comment by tonyc** [comment]
Going with option #4 per discussion
